server:
  port: 9090 #项目端口号
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_vue?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&useSSl=false
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true   # 格式化 SQL，便于阅读
        use_sql_comments: true  # 可选，在 SQL 中显示注释说明是什么操作

logging:
  file:
    name: logs/app.log          # 指定日志文件名和路径（相对或绝对路径）
    # path: /var/logs           # 或者只指定目录，文件名默认为 spring.log
  level:
    com.example: DEBUG           # 设置特定包的日志级别（可选）
    org.hibernate.SQL: DEBUG   # 打印 SQL
    org.hibernate.orm.jdbc.bind: TRACE  # 打印 SQL 参数（Spring Boot 3.x / Hibernate 6 使用这个）

    l.BasicBinder: TRACE