server:
  port: 9090 #项目端口号
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_vue?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&useSSl=false
    username: root
    password: root

logging:
  file:
    name: logs/app.log          # 指定日志文件名和路径（相对或绝对路径）
    # path: /var/logs           # 或者只指定目录，文件名默认为 spring.log
  level:
    com.example: DEBUG           # 设置特定包的日志级别（可选）